// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectOpenFile(arg1) {
  return window['go']['main']['App']['DirectOpenFile'](arg1);
}

export function GetFilesToOpenOnStartup() {
  return window['go']['main']['App']['GetFilesToOpenOnStartup']();
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RegisterFileAssociations() {
  return window['go']['main']['App']['RegisterFileAssociations']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
