// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectOpenFile(arg1:string):Promise<void>;

export function GetFilesToOpenOnStartup():Promise<Array<string>>;

export function IsInitialized():Promise<boolean>;

export function OpenFile(arg1:string):Promise<Array<number>>;

export function OpenFileDialog():Promise<Array<string>>;

export function RegisterFileAssociations():Promise<boolean>;

export function SaveFile(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;
